name: Deploy Publii Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main website
        uses: actions/checkout@v4

      - name: Checkout Publii site
        uses: actions/checkout@v4
        with:
          repository: fidellp99/artigos
          path: artigos-source
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove old artigos folder
        run: |
          rm -rf artigos

      - name: Copy Publii files
        run: |
          cp -R artigos-source/. artigos/

      - name: Remove Git files
        run: |
          rm -rf artigos/.git
          rm -rf artigos/.github

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add artigos/

          if git diff --cached --quiet; then
            echo "No changes to deploy."
          else
            git commit -m "Deploy Publii site"
            git push
          fi
